name: Test & Deploy to Vercel

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: image:node 20
    steps:
      - run: npm ci
      - run: npm test
      - run: npm run build
